name = "test-runner"
main = "worker/testRunner.js"
compatibility_date = "2024-06-20"

[triggers]
crons = ["1 0 * * *", "13 15 * * *"]

[kv_namespaces]
[[kv_namespaces]]
binding = "AUDIT_LOG"
id = "your_kv_namespace_id"

[vars]
APPS_SCRIPT_URL = "https://Apps Script here"
# SECURITY_EMAIL and PRIVATE_KEY should be added via `wrangler secret put`
