name = "contact-intake"
main = "worker-contact.js"
compatibility_date = "2024-01-30"

# Uncomment and provide your KV namespace ID to enable persistence
# kv_namespaces = [
#   { binding = "CONTACT_KV", id = "<your-kv-id>" }
# ]
