name = "join-intake"
main = "worker-join.js"
compatibility_date = "2024-01-30"
[vars]
ALLOWED_ORIGINS = "https://www.opsonlinesupport.com"
ASSET_ID = "ops-join-intake"
TRANSIT_URL = "https://ops-transit-broker.pure-sail-sole.workers.dev"
MAX_BODY_BYTES = "256000"
MAX_FIELD_BYTES = "5000"

# Uncomment and provide your KV namespace ID to enable persistence
# kv_namespaces = [
#   { binding = "JOIN_KV", id = "<your-kv-id>" }
# ]
