# GitHub Actions workflow to deploy a React project to Cloudflare Pages
name: Deploy to Cloudflare Pages

# Triggers the workflow on push events to the 'main' branch
on:
  push:
    branches:
      - main

# Define a single job named 'deploy'
jobs:
  deploy:
    # Specifies the runner environment for the job
    runs-on: ubuntu-latest

    # Sequence of steps to be executed in the job
    steps:
      # Checks out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Specifies the Node.js version to use
          node-version: '20' # You can specify 'lts/*' or a specific version like '18'

      # Installs project dependencies using 'npm ci' for clean installs in CI environments
      - name: Install dependencies
        run: npm ci

      # Builds the React project
      - name: Build project
        run: npm run build

      # Deploys the built project to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          # Cloudflare API token stored as a GitHub secret
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Cloudflare Account ID stored as a GitHub secret
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # The name of your Cloudflare Pages project
          projectName: your-project-name
          # The directory where the built static assets are located
          directory: dist
          # Optionally, specify the Git branch to deploy from (defaults to the current branch)
          # branch: ${{ github.ref_name }}
